- id: format-dockerfiles
  additional_dependencies:
    - dockerfile-parse
  description: format dockerfiles
  entry: format-dockerfile
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: format dockerfiles
  types: ["dockerfile"]
- id: python-print-detection
  entry: print-detection
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: detect print on python code
  types: ["python"]
