- id: format-dockerfiles
  additional_dependencies:
    - dockerfile-parse
  description: format dockerfiles
  entry: format-dockerfile
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: format dockerfiles
  types: ["dockerfile"]
- id: python-print-detection
  entry: print-detection
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: detect print on python code
  types: ["python"]
- id: python-pprint-detection
  entry: pprint-detection
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: detect pprint on python code
  types: ["python"]
- id: pylint-html-report
  name: pylint html report
  description: genereate htmll report
  entry: precommit_tools/pylint-report-html.sh
  language: script
