- id: format-dockerfiles
  additional_dependencies:
      - dockerfile-parse
  description: format dockerfiles
  entry: format-dockerfile
  language: python
  language_version: '3.10'
  minimum_pre_commit_version: '2.20.0'
  name: format dockerfiles
  types: ["dockerfile"]
- id: print-detection
  entry: pre_commit_hooks/bash/print_detection.sh
  language: script
  minimum_pre_commit_version: '2.20.0'
  name: detect print on python code
  types: ["python"]
