- id: format-dockerfiles
  description: format dockerfiles
  entry: pre_commit_hooks/python/format_dockerfile.py
  language: python
  name: format dockerfiles
  types: ["dockerfile"]
  additional_dependencies:
    - dockerfile-parse
- id: print-detection
  entry: scripts/pre_commit_hooks/bassh/print_detection.sh
  files: .py
  language: script
  name: detect print on python code
  stages:
      - commit
      - manual
  types: [python]
